rk-mpp-service-objs := mpp_service.o
rk-mpp-device-objs := mpp_dev_common.o mpp_iommu_dma.o
rk-mpp-vdec-objs := mpp_dev_rkvdec.o
rk-mpp-vdpu1-objs := mpp_dev_vdpu1.o
rk-mpp-vdpu2-objs := mpp_dev_vdpu2.o
rk-mpp-vepu1-objs := mpp_dev_vepu1.o
rk-mpp-vepu2-objs := mpp_dev_vepu2.o

#obj-$(CONFIG_ROCKCHIP_MPP_SERVICE) += rk-mpp-service.o
#obj-$(CONFIG_ROCKCHIP_MPP_DEVICE) += rk-mpp-device.o
#obj-$(CONFIG_ROCKCHIP_MPP_VDEC_DEVICE) += rk-mpp-vdec.o
#obj-$(CONFIG_ROCKCHIP_MPP_VDPU1_DEVICE) += rk-mpp-vdpu1.o
#obj-$(CONFIG_ROCKCHIP_MPP_VEPU1_DEVICE) += rk-mpp-vepu1.o
#obj-$(CONFIG_ROCKCHIP_MPP_VDPU2_DEVICE) += rk-mpp-vdpu2.o
#obj-$(CONFIG_ROCKCHIP_MPP_VEPU2_DEVICE) += rk-mpp-vepu2.o

obj-m += rk-mpp-service.o
obj-m += rk-mpp-device.o
obj-m += rk-mpp-vdec.o
obj-m += rk-mpp-vdpu1.o
obj-m += rk-mpp-vepu1.o
obj-m += rk-mpp-vdpu2.o
obj-m += rk-mpp-vepu2.o

